<?php

use Illuminate\Database\Seeder;
use App\News;

class NewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $news = new News();
      $news->title = "Random 1";
      $news->slug = "1-random";
      $news->content = "Generated by very secret method.";
      $news->save();

        $news = new News();
        $news->title = "Random 2";
        $news->slug = "2-random";
        $news->content = "Generated by very secret method.";
        $news->save();

        $news = new News();
        $news->title = "Random 3";
        $news->slug = "3-random";
        $news->content = "Generated by very secret method.";
        $news->save();
    }
}
